// @generated by protoc-gen-connect-es v0.8.6
// @generated from file stability_api/platform/generation/v1/generation.proto (package stabilityai.platformapis.generation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Answer, ChainRequest, Request } from "./generation_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 *
 * gRPC services
 *
 *
 * @generated from service stabilityai.platformapis.generation.v1.GenerationService
 */
export declare const GenerationService: {
  readonly typeName: "stabilityai.platformapis.generation.v1.GenerationService",
  readonly methods: {
    /**
     * @generated from rpc stabilityai.platformapis.generation.v1.GenerationService.Generate
     */
    readonly generate: {
      readonly name: "Generate",
      readonly I: typeof Request,
      readonly O: typeof Answer,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc stabilityai.platformapis.generation.v1.GenerationService.ChainGenerate
     */
    readonly chainGenerate: {
      readonly name: "ChainGenerate",
      readonly I: typeof ChainRequest,
      readonly O: typeof Answer,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

