// @generated by protoc-gen-connect-es v0.12.0
// @generated from file stability_api/platform/finetuning/finetuning.proto (package gooseai, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateModelRequest, CreateModelResponse, DeleteModelRequest, DeleteModelResponse, GetModelRequest, GetModelResponse, ListModelsRequest, ListModelsResponse, ResubmitModelRequest, ResubmitModelResponse, UpdateModelRequest, UpdateModelResponse } from "./finetuning_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service gooseai.FineTuningService
 */
export declare const FineTuningService: {
  readonly typeName: "gooseai.FineTuningService",
  readonly methods: {
    /**
     * Create a new model and begin the fine tuning process
     *
     * @generated from rpc gooseai.FineTuningService.CreateModel
     */
    readonly createModel: {
      readonly name: "CreateModel",
      readonly I: typeof CreateModelRequest,
      readonly O: typeof CreateModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Get a FineTuningModel
     *
     * @generated from rpc gooseai.FineTuningService.GetModel
     */
    readonly getModel: {
      readonly name: "GetModel",
      readonly I: typeof GetModelRequest,
      readonly O: typeof GetModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Update a FineTuningModel by id
     *
     * @generated from rpc gooseai.FineTuningService.UpdateModel
     */
    readonly updateModel: {
      readonly name: "UpdateModel",
      readonly I: typeof UpdateModelRequest,
      readonly O: typeof UpdateModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Delete a fine tuned model
     *
     * @generated from rpc gooseai.FineTuningService.DeleteModel
     */
    readonly deleteModel: {
      readonly name: "DeleteModel",
      readonly I: typeof DeleteModelRequest,
      readonly O: typeof DeleteModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Re-run training, does not create a new model
     *
     * @generated from rpc gooseai.FineTuningService.ResubmitModel
     */
    readonly resubmitModel: {
      readonly name: "ResubmitModel",
      readonly I: typeof ResubmitModelRequest,
      readonly O: typeof ResubmitModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * List all the fine tuned models for an organization or user
     *
     * @generated from rpc gooseai.FineTuningService.ListModels
     */
    readonly listModels: {
      readonly name: "ListModels",
      readonly I: typeof ListModelsRequest,
      readonly O: typeof ListModelsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

