# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import finetuning_pb2 as finetuning__pb2


class FineTuningServiceStub(object):
    """TODO: should we add a list of jobs by userId / orgId?
    TODO: should we add a list of jobs by status?
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFineTuningJob = channel.unary_unary(
                '/gooseai.FineTuningService/CreateFineTuningJob',
                request_serializer=finetuning__pb2.CreateFineTuningJobRequest.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJob.FromString,
                )
        self.GetFineTuningJobById = channel.unary_unary(
                '/gooseai.FineTuningService/GetFineTuningJobById',
                request_serializer=finetuning__pb2.FineTuningJobRequestById.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJob.FromString,
                )
        self.UpdateFineTuningJob = channel.unary_unary(
                '/gooseai.FineTuningService/UpdateFineTuningJob',
                request_serializer=finetuning__pb2.UpdateFineTuningJobRequest.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJob.FromString,
                )
        self.DeleteFineTuningJob = channel.unary_unary(
                '/gooseai.FineTuningService/DeleteFineTuningJob',
                request_serializer=finetuning__pb2.FineTuningJobRequestById.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJob.FromString,
                )
        self.GetFineTuningJobProgress = channel.unary_unary(
                '/gooseai.FineTuningService/GetFineTuningJobProgress',
                request_serializer=finetuning__pb2.FineTuningJobRequestById.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJobStatus.FromString,
                )
        self.ResubmitFineTuningJob = channel.unary_unary(
                '/gooseai.FineTuningService/ResubmitFineTuningJob',
                request_serializer=finetuning__pb2.ResubmitFineTuningJobRequest.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJob.FromString,
                )
        self.GetJobsByUserId = channel.unary_unary(
                '/gooseai.FineTuningService/GetJobsByUserId',
                request_serializer=finetuning__pb2.FineTuningJobRequestByUserId.SerializeToString,
                response_deserializer=finetuning__pb2.FineTuningJobList.FromString,
                )


class FineTuningServiceServicer(object):
    """TODO: should we add a list of jobs by userId / orgId?
    TODO: should we add a list of jobs by status?
    """

    def CreateFineTuningJob(self, request, context):
        """Create a new project if it does not exist, and runs it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFineTuningJobById(self, request, context):
        """Get a FineTuningJob by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFineTuningJob(self, request, context):
        """Update a FineTuningJob by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFineTuningJob(self, request, context):
        """Delete a FineTuningJob by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFineTuningJobProgress(self, request, context):
        """Check the progress of a FineTuningJob by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResubmitFineTuningJob(self, request, context):
        """Re-run training API call, does not create a new job in the DB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobsByUserId(self, request, context):
        """Get a list of FineTuningJobs by user id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FineTuningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFineTuningJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFineTuningJob,
                    request_deserializer=finetuning__pb2.CreateFineTuningJobRequest.FromString,
                    response_serializer=finetuning__pb2.FineTuningJob.SerializeToString,
            ),
            'GetFineTuningJobById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFineTuningJobById,
                    request_deserializer=finetuning__pb2.FineTuningJobRequestById.FromString,
                    response_serializer=finetuning__pb2.FineTuningJob.SerializeToString,
            ),
            'UpdateFineTuningJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFineTuningJob,
                    request_deserializer=finetuning__pb2.UpdateFineTuningJobRequest.FromString,
                    response_serializer=finetuning__pb2.FineTuningJob.SerializeToString,
            ),
            'DeleteFineTuningJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFineTuningJob,
                    request_deserializer=finetuning__pb2.FineTuningJobRequestById.FromString,
                    response_serializer=finetuning__pb2.FineTuningJob.SerializeToString,
            ),
            'GetFineTuningJobProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFineTuningJobProgress,
                    request_deserializer=finetuning__pb2.FineTuningJobRequestById.FromString,
                    response_serializer=finetuning__pb2.FineTuningJobStatus.SerializeToString,
            ),
            'ResubmitFineTuningJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ResubmitFineTuningJob,
                    request_deserializer=finetuning__pb2.ResubmitFineTuningJobRequest.FromString,
                    response_serializer=finetuning__pb2.FineTuningJob.SerializeToString,
            ),
            'GetJobsByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobsByUserId,
                    request_deserializer=finetuning__pb2.FineTuningJobRequestByUserId.FromString,
                    response_serializer=finetuning__pb2.FineTuningJobList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gooseai.FineTuningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FineTuningService(object):
    """TODO: should we add a list of jobs by userId / orgId?
    TODO: should we add a list of jobs by status?
    """

    @staticmethod
    def CreateFineTuningJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/CreateFineTuningJob',
            finetuning__pb2.CreateFineTuningJobRequest.SerializeToString,
            finetuning__pb2.FineTuningJob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFineTuningJobById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/GetFineTuningJobById',
            finetuning__pb2.FineTuningJobRequestById.SerializeToString,
            finetuning__pb2.FineTuningJob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFineTuningJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/UpdateFineTuningJob',
            finetuning__pb2.UpdateFineTuningJobRequest.SerializeToString,
            finetuning__pb2.FineTuningJob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFineTuningJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/DeleteFineTuningJob',
            finetuning__pb2.FineTuningJobRequestById.SerializeToString,
            finetuning__pb2.FineTuningJob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFineTuningJobProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/GetFineTuningJobProgress',
            finetuning__pb2.FineTuningJobRequestById.SerializeToString,
            finetuning__pb2.FineTuningJobStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResubmitFineTuningJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/ResubmitFineTuningJob',
            finetuning__pb2.ResubmitFineTuningJobRequest.SerializeToString,
            finetuning__pb2.FineTuningJob.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobsByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gooseai.FineTuningService/GetJobsByUserId',
            finetuning__pb2.FineTuningJobRequestByUserId.SerializeToString,
            finetuning__pb2.FineTuningJobList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
