// @generated by protoc-gen-es v1.2.0
// @generated from file stability_api/platform/engines/v1/engines.proto (package stabilityai.platformapis.engines.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Possible engine type
 *
 * @generated from enum stabilityai.platformapis.engines.v1.EngineType
 */
export const EngineType = proto3.makeEnum(
  "stabilityai.platformapis.engines.v1.EngineType",
  [
    {no: 0, name: "TEXT"},
    {no: 1, name: "PICTURE"},
    {no: 2, name: "AUDIO"},
    {no: 3, name: "VIDEO"},
    {no: 4, name: "CLASSIFICATION"},
    {no: 5, name: "STORAGE"},
  ],
);

/**
 * @generated from enum stabilityai.platformapis.engines.v1.EngineTokenizer
 */
export const EngineTokenizer = proto3.makeEnum(
  "stabilityai.platformapis.engines.v1.EngineTokenizer",
  [
    {no: 0, name: "GPT2"},
    {no: 1, name: "PILE"},
  ],
);

/**
 * Engine info struct
 *
 * @generated from message stabilityai.platformapis.engines.v1.EngineInfo
 */
export const EngineInfo = proto3.makeMessageType(
  "stabilityai.platformapis.engines.v1.EngineInfo",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "ready", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "type", kind: "enum", T: proto3.getEnumType(EngineType) },
    { no: 5, name: "tokenizer", kind: "enum", T: proto3.getEnumType(EngineTokenizer) },
    { no: 6, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "can_fine_tune", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "is_adaptive", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * Empty
 *
 * @generated from message stabilityai.platformapis.engines.v1.ListEnginesRequest
 */
export const ListEnginesRequest = proto3.makeMessageType(
  "stabilityai.platformapis.engines.v1.ListEnginesRequest",
  [],
);

/**
 * Engine info list
 *
 * @generated from message stabilityai.platformapis.engines.v1.Engines
 */
export const Engines = proto3.makeMessageType(
  "stabilityai.platformapis.engines.v1.Engines",
  () => [
    { no: 1, name: "engine", kind: "message", T: EngineInfo, repeated: true },
  ],
);

